package com.porfirio.fraccionando.gui.pantallas;

import com.porfirio.fraccionando.dominio.logica.fracciones.Fraccion;

/**
 * Esta clase es una extension de JPanel, su objetivo es proporcionar la
 * interface para ingresar fracciones en las operaciones de la aplicacion.
 *
 * @author Porfirio Angel Diaz Sanchez <porfirioads@gmail.com>
 */
public class FraccionPanel extends javax.swing.JPanel {

    private Fraccion fraccion;
    private boolean botonesReiniciarRemover;

    public FraccionPanel(boolean botonesReiniciarRemover) {
        this.botonesReiniciarRemover = botonesReiniciarRemover;
        initComponents();
        iniciarGUI();
    }

    /**
     * Creates new form FraccionPanel
     */
    public FraccionPanel() {
        this.botonesReiniciarRemover = true;
        initComponents();
        iniciarGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButtonNum_7 = new javax.swing.JButton();
        jButtonNum_8 = new javax.swing.JButton();
        jButtonNum_9 = new javax.swing.JButton();
        jButtonNum_4 = new javax.swing.JButton();
        jButtonNum_5 = new javax.swing.JButton();
        jButtonNum_6 = new javax.swing.JButton();
        jButtonNum_1 = new javax.swing.JButton();
        jButtonNum_2 = new javax.swing.JButton();
        jButtonNum_3 = new javax.swing.JButton();
        jButtonNum_0 = new javax.swing.JButton();
        jButtonNumAc = new javax.swing.JButton();
        jButtonNumDel = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButtonDen_7 = new javax.swing.JButton();
        jButtonDen_8 = new javax.swing.JButton();
        jButtonDen_9 = new javax.swing.JButton();
        jButtonDen_4 = new javax.swing.JButton();
        jButtonDen_5 = new javax.swing.JButton();
        jButtonDen_6 = new javax.swing.JButton();
        jButtonDen_1 = new javax.swing.JButton();
        jButtonDen_2 = new javax.swing.JButton();
        jButtonDen_3 = new javax.swing.JButton();
        jButtonDen_0 = new javax.swing.JButton();
        jButtonDenAc = new javax.swing.JButton();
        jButtonDenDel = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButtonEnt_7 = new javax.swing.JButton();
        jButtonEnt_8 = new javax.swing.JButton();
        jButtonEnt_9 = new javax.swing.JButton();
        jButtonEnt_4 = new javax.swing.JButton();
        jButtonEnt_5 = new javax.swing.JButton();
        jButtonEnt_6 = new javax.swing.JButton();
        jButtonEnt_1 = new javax.swing.JButton();
        jButtonEnt_2 = new javax.swing.JButton();
        jButtonEnt_3 = new javax.swing.JButton();
        jButtonEnt_0 = new javax.swing.JButton();
        jButtonEntAc = new javax.swing.JButton();
        jButtonEntDel = new javax.swing.JButton();
        jButtonReiniciarFraccion = new javax.swing.JButton();
        jButtonRemoverFraccion = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Fracción"));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jPanel7.setMinimumSize(null);
        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(null);
        jPanel7.setLayout(new java.awt.GridLayout(2, 1));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Numerador"));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.GridLayout(4, 3));

        jButtonNum_7.setText("7");
        jPanel8.add(jButtonNum_7);

        jButtonNum_8.setText("8");
        jPanel8.add(jButtonNum_8);

        jButtonNum_9.setText("9");
        jPanel8.add(jButtonNum_9);

        jButtonNum_4.setText("4");
        jPanel8.add(jButtonNum_4);

        jButtonNum_5.setText("5");
        jPanel8.add(jButtonNum_5);

        jButtonNum_6.setText("6");
        jPanel8.add(jButtonNum_6);

        jButtonNum_1.setText("1");
        jPanel8.add(jButtonNum_1);

        jButtonNum_2.setText("2");
        jPanel8.add(jButtonNum_2);

        jButtonNum_3.setText("3");
        jPanel8.add(jButtonNum_3);

        jButtonNum_0.setText("0");
        jPanel8.add(jButtonNum_0);

        jButtonNumAc.setBackground(new java.awt.Color(204, 0, 0));
        jButtonNumAc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNumAc.setText("AC");
        jButtonNumAc.setEnabled(false);
        jPanel8.add(jButtonNumAc);

        jButtonNumDel.setBackground(new java.awt.Color(204, 0, 0));
        jButtonNumDel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNumDel.setText("DEL");
        jButtonNumDel.setEnabled(false);
        jPanel8.add(jButtonNumDel);

        jPanel7.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Denominador"));
        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.GridLayout(4, 3));

        jButtonDen_7.setText("7");
        jPanel9.add(jButtonDen_7);

        jButtonDen_8.setText("8");
        jPanel9.add(jButtonDen_8);

        jButtonDen_9.setText("9");
        jPanel9.add(jButtonDen_9);

        jButtonDen_4.setText("4");
        jPanel9.add(jButtonDen_4);

        jButtonDen_5.setText("5");
        jPanel9.add(jButtonDen_5);

        jButtonDen_6.setText("6");
        jPanel9.add(jButtonDen_6);

        jButtonDen_1.setText("1");
        jPanel9.add(jButtonDen_1);

        jButtonDen_2.setText("2");
        jPanel9.add(jButtonDen_2);

        jButtonDen_3.setText("3");
        jPanel9.add(jButtonDen_3);

        jButtonDen_0.setText("0");
        jPanel9.add(jButtonDen_0);

        jButtonDenAc.setBackground(new java.awt.Color(204, 0, 0));
        jButtonDenAc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDenAc.setText("AC");
        jButtonDenAc.setEnabled(false);
        jPanel9.add(jButtonDenAc);

        jButtonDenDel.setBackground(new java.awt.Color(204, 0, 0));
        jButtonDenDel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDenDel.setText("DEL");
        jButtonDenDel.setEnabled(false);
        jPanel9.add(jButtonDenDel);

        jPanel7.add(jPanel9);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel7, gridBagConstraints);

        jPanel10.setMinimumSize(null);
        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(null);
        jPanel10.setLayout(new java.awt.GridBagLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Entero"));
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(null);
        jPanel6.setLayout(new java.awt.GridLayout(4, 3));

        jButtonEnt_7.setText("7");
        jPanel6.add(jButtonEnt_7);

        jButtonEnt_8.setText("8");
        jPanel6.add(jButtonEnt_8);

        jButtonEnt_9.setText("9");
        jPanel6.add(jButtonEnt_9);

        jButtonEnt_4.setText("4");
        jPanel6.add(jButtonEnt_4);

        jButtonEnt_5.setText("5");
        jPanel6.add(jButtonEnt_5);

        jButtonEnt_6.setText("6");
        jPanel6.add(jButtonEnt_6);

        jButtonEnt_1.setText("1");
        jPanel6.add(jButtonEnt_1);

        jButtonEnt_2.setText("2");
        jPanel6.add(jButtonEnt_2);

        jButtonEnt_3.setText("3");
        jPanel6.add(jButtonEnt_3);

        jButtonEnt_0.setText("0");
        jPanel6.add(jButtonEnt_0);

        jButtonEntAc.setBackground(new java.awt.Color(204, 0, 0));
        jButtonEntAc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEntAc.setText("AC");
        jButtonEntAc.setEnabled(false);
        jPanel6.add(jButtonEntAc);

        jButtonEntDel.setBackground(new java.awt.Color(204, 0, 0));
        jButtonEntDel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEntDel.setText("DEL");
        jButtonEntDel.setEnabled(false);
        jPanel6.add(jButtonEntDel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.ipady = 149;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel10.add(jPanel6, gridBagConstraints);

        jButtonReiniciarFraccion.setText("Reiniciar");
        jButtonReiniciarFraccion.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel10.add(jButtonReiniciarFraccion, gridBagConstraints);

        jButtonRemoverFraccion.setText("Remover");
        jButtonRemoverFraccion.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel10.add(jButtonRemoverFraccion, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel10, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDenAc;
    private javax.swing.JButton jButtonDenDel;
    private javax.swing.JButton jButtonDen_0;
    private javax.swing.JButton jButtonDen_1;
    private javax.swing.JButton jButtonDen_2;
    private javax.swing.JButton jButtonDen_3;
    private javax.swing.JButton jButtonDen_4;
    private javax.swing.JButton jButtonDen_5;
    private javax.swing.JButton jButtonDen_6;
    private javax.swing.JButton jButtonDen_7;
    private javax.swing.JButton jButtonDen_8;
    private javax.swing.JButton jButtonDen_9;
    private javax.swing.JButton jButtonEntAc;
    private javax.swing.JButton jButtonEntDel;
    private javax.swing.JButton jButtonEnt_0;
    private javax.swing.JButton jButtonEnt_1;
    private javax.swing.JButton jButtonEnt_2;
    private javax.swing.JButton jButtonEnt_3;
    private javax.swing.JButton jButtonEnt_4;
    private javax.swing.JButton jButtonEnt_5;
    private javax.swing.JButton jButtonEnt_6;
    private javax.swing.JButton jButtonEnt_7;
    private javax.swing.JButton jButtonEnt_8;
    private javax.swing.JButton jButtonEnt_9;
    private javax.swing.JButton jButtonNumAc;
    private javax.swing.JButton jButtonNumDel;
    private javax.swing.JButton jButtonNum_0;
    private javax.swing.JButton jButtonNum_1;
    private javax.swing.JButton jButtonNum_2;
    private javax.swing.JButton jButtonNum_3;
    private javax.swing.JButton jButtonNum_4;
    private javax.swing.JButton jButtonNum_5;
    private javax.swing.JButton jButtonNum_6;
    private javax.swing.JButton jButtonNum_7;
    private javax.swing.JButton jButtonNum_8;
    private javax.swing.JButton jButtonNum_9;
    private javax.swing.JButton jButtonReiniciarFraccion;
    private javax.swing.JButton jButtonRemoverFraccion;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables

    /**
     * Inicializa aspectos de la gui, que no se pueden colocar en el metodo
     * initComponents.
     */
    private void iniciarGUI() {
        jButtonReiniciarFraccion.setVisible(botonesReiniciarRemover);
        jButtonRemoverFraccion.setVisible(botonesReiniciarRemover);
    }

    public Fraccion getFraccion() {
        return fraccion;
    }

    public boolean hasBotonesReiniciarRemover() {
        return botonesReiniciarRemover;
    }

}
