package com.porfirio.fraccionando.gui.pantallas;

import com.porfirio.fraccionando.main.Configuracion;
import java.awt.Component;
import java.awt.Font;
import javax.accessibility.Accessible;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Porfirio Angel Diaz Sanchez <porfirioads@gmail.com>
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        iniciarGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupTemas = new javax.swing.ButtonGroup();
        buttonGroupIdiomas = new javax.swing.ButtonGroup();
        buttonGroupExplicaciones = new javax.swing.ButtonGroup();
        jPanelFondoOscuro = new javax.swing.JPanel();
        jPanelFondoClaro = new javax.swing.JPanel();
        jPanelVista = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanelDerecho = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jPanelCalculadora = new javax.swing.JPanel();
        fraccionPanel1 = new com.porfirio.fraccionando.gui.pantallas.FraccionPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonMas = new javax.swing.JButton();
        jButtonMenos = new javax.swing.JButton();
        jButtonPor = new javax.swing.JButton();
        jButtonEntre = new javax.swing.JButton();
        jButtonEquivalentes = new javax.swing.JButton();
        jButtonReciprocas = new javax.swing.JButton();
        jButtonMayor = new javax.swing.JButton();
        jButtonSimplificar = new javax.swing.JButton();
        jButtonCam = new javax.swing.JButton();
        jButtonCai = new javax.swing.JButton();
        jButtonMcm = new javax.swing.JButton();
        jButtonMcd = new javax.swing.JButton();
        jPanelEnvio = new javax.swing.JPanel();
        jButtonResolverOperacion = new javax.swing.JButton();
        jButtonReiniciarOperacion = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jmItemNuevo = new javax.swing.JMenuItem();
        jmItemGuardar = new javax.swing.JMenuItem();
        jmItemSalir = new javax.swing.JMenuItem();
        jMenuPreferencias = new javax.swing.JMenu();
        jMenuTema = new javax.swing.JMenu();
        jrbItemAzul = new javax.swing.JRadioButtonMenuItem();
        jrbItemAmarillo = new javax.swing.JRadioButtonMenuItem();
        jrbItemRosa = new javax.swing.JRadioButtonMenuItem();
        jrbItemRojo = new javax.swing.JRadioButtonMenuItem();
        jrbItemMorado = new javax.swing.JRadioButtonMenuItem();
        jMenuIdioma = new javax.swing.JMenu();
        jrbItemEspanol = new javax.swing.JRadioButtonMenuItem();
        jrbItemIngles = new javax.swing.JRadioButtonMenuItem();
        jMenuExplicacion = new javax.swing.JMenu();
        jrbItemSimple = new javax.swing.JRadioButtonMenuItem();
        jrbItemDetallada = new javax.swing.JRadioButtonMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jmItemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fraccionando");
        setSize(new java.awt.Dimension(1000, 562));

        jPanelFondoOscuro.setBackground(Configuracion.colorOscuro);
        jPanelFondoOscuro.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelFondoOscuro.setLayout(new java.awt.BorderLayout());

        jPanelFondoClaro.setBackground(Configuracion.colorClaro);
        jPanelFondoClaro.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelFondoClaro.setLayout(new java.awt.BorderLayout());

        jPanelVista.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVista.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelVista.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));
        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanelVista.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Explicación"));
        jPanel3.setOpaque(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        jPanelVista.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrada"));
        jPanel4.setOpaque(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanelVista.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanelFondoClaro.add(jPanelVista, java.awt.BorderLayout.CENTER);

        jPanelDerecho.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jPanelDerecho.setOpaque(false);
        jPanelDerecho.setLayout(new java.awt.BorderLayout());

        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane.setRequestFocusEnabled(false);

        jPanelCalculadora.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 20));
        jPanelCalculadora.setOpaque(false);
        jPanelCalculadora.setLayout(new javax.swing.BoxLayout(jPanelCalculadora, javax.swing.BoxLayout.Y_AXIS));

        fraccionPanel1.setOpaque(false);
        jPanelCalculadora.add(fraccionPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones"));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jButtonMas.setText("+");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jButtonMas, gridBagConstraints);

        jButtonMenos.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jButtonMenos, gridBagConstraints);

        jButtonPor.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jButtonPor, gridBagConstraints);

        jButtonEntre.setText("÷");
        jButtonEntre.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jButtonEntre, gridBagConstraints);

        jButtonEquivalentes.setText("Equivalentes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jButtonEquivalentes, gridBagConstraints);

        jButtonReciprocas.setText("Recíprocas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jButtonReciprocas, gridBagConstraints);

        jButtonMayor.setText("Mayor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jButtonMayor, gridBagConstraints);

        jButtonSimplificar.setText("Simplificar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jButtonSimplificar, gridBagConstraints);

        jButtonCam.setText("C.A.M.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jButtonCam, gridBagConstraints);

        jButtonCai.setText("C.A.I.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jButtonCai, gridBagConstraints);

        jButtonMcm.setText("M.C.M.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jButtonMcm, gridBagConstraints);

        jButtonMcd.setText("M.C.D.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jButtonMcd, gridBagConstraints);

        jPanelCalculadora.add(jPanel2);

        jScrollPane.setViewportView(jPanelCalculadora);

        jPanelDerecho.add(jScrollPane, java.awt.BorderLayout.CENTER);

        jPanelEnvio.setOpaque(false);
        jPanelEnvio.setPreferredSize(new java.awt.Dimension(81, 100));
        jPanelEnvio.setLayout(new java.awt.GridLayout(2, 1));

        jButtonResolverOperacion.setText("Resolver");
        jPanelEnvio.add(jButtonResolverOperacion);

        jButtonReiniciarOperacion.setText("Reiniciar");
        jPanelEnvio.add(jButtonReiniciarOperacion);

        jPanelDerecho.add(jPanelEnvio, java.awt.BorderLayout.SOUTH);

        jPanelFondoClaro.add(jPanelDerecho, java.awt.BorderLayout.EAST);

        jPanelFondoOscuro.add(jPanelFondoClaro, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelFondoOscuro, java.awt.BorderLayout.CENTER);

        jMenuArchivo.setText("Archivo");

        jmItemNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jmItemNuevo.setText("Nuevo");
        jMenuArchivo.add(jmItemNuevo);

        jmItemGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jmItemGuardar.setText("Guardar");
        jMenuArchivo.add(jmItemGuardar);

        jmItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmItemSalir.setText("Salir");
        jMenuArchivo.add(jmItemSalir);

        jMenuBar.add(jMenuArchivo);

        jMenuPreferencias.setText("Preferencias");

        jMenuTema.setText("Tema");

        buttonGroupTemas.add(jrbItemAzul);
        jrbItemAzul.setSelected(true);
        jrbItemAzul.setText("Azul");
        jMenuTema.add(jrbItemAzul);

        buttonGroupTemas.add(jrbItemAmarillo);
        jrbItemAmarillo.setText("Amarillo");
        jMenuTema.add(jrbItemAmarillo);

        buttonGroupTemas.add(jrbItemRosa);
        jrbItemRosa.setText("Rosa");
        jMenuTema.add(jrbItemRosa);

        buttonGroupTemas.add(jrbItemRojo);
        jrbItemRojo.setText("Rojo");
        jMenuTema.add(jrbItemRojo);

        buttonGroupTemas.add(jrbItemMorado);
        jrbItemMorado.setText("Morado");
        jMenuTema.add(jrbItemMorado);

        jMenuPreferencias.add(jMenuTema);

        jMenuIdioma.setText("Idioma");

        buttonGroupIdiomas.add(jrbItemEspanol);
        jrbItemEspanol.setSelected(true);
        jrbItemEspanol.setText("Español");
        jMenuIdioma.add(jrbItemEspanol);

        buttonGroupIdiomas.add(jrbItemIngles);
        jrbItemIngles.setText("Inglés");
        jMenuIdioma.add(jrbItemIngles);

        jMenuPreferencias.add(jMenuIdioma);

        jMenuExplicacion.setText("Explicación");

        buttonGroupExplicaciones.add(jrbItemSimple);
        jrbItemSimple.setText("Simple");
        jMenuExplicacion.add(jrbItemSimple);

        buttonGroupExplicaciones.add(jrbItemDetallada);
        jrbItemDetallada.setSelected(true);
        jrbItemDetallada.setText("Detallada");
        jMenuExplicacion.add(jrbItemDetallada);

        jMenuPreferencias.add(jMenuExplicacion);

        jMenuBar.add(jMenuPreferencias);

        jMenuAyuda.setText("Ayuda");

        jmItemAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jmItemAcercaDe.setText("Acerca de...");
        jMenuAyuda.add(jmItemAcercaDe);

        jMenuBar.add(jMenuAyuda);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupExplicaciones;
    private javax.swing.ButtonGroup buttonGroupIdiomas;
    private javax.swing.ButtonGroup buttonGroupTemas;
    private com.porfirio.fraccionando.gui.pantallas.FraccionPanel fraccionPanel1;
    private javax.swing.JButton jButtonCai;
    private javax.swing.JButton jButtonCam;
    private javax.swing.JButton jButtonEntre;
    private javax.swing.JButton jButtonEquivalentes;
    private javax.swing.JButton jButtonMas;
    private javax.swing.JButton jButtonMayor;
    private javax.swing.JButton jButtonMcd;
    private javax.swing.JButton jButtonMcm;
    private javax.swing.JButton jButtonMenos;
    private javax.swing.JButton jButtonPor;
    private javax.swing.JButton jButtonReciprocas;
    private javax.swing.JButton jButtonReiniciarOperacion;
    private javax.swing.JButton jButtonResolverOperacion;
    private javax.swing.JButton jButtonSimplificar;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuExplicacion;
    private javax.swing.JMenu jMenuIdioma;
    private javax.swing.JMenu jMenuPreferencias;
    private javax.swing.JMenu jMenuTema;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelCalculadora;
    private javax.swing.JPanel jPanelDerecho;
    private javax.swing.JPanel jPanelEnvio;
    private javax.swing.JPanel jPanelFondoClaro;
    private javax.swing.JPanel jPanelFondoOscuro;
    private javax.swing.JPanel jPanelVista;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JMenuItem jmItemAcercaDe;
    private javax.swing.JMenuItem jmItemGuardar;
    private javax.swing.JMenuItem jmItemNuevo;
    private javax.swing.JMenuItem jmItemSalir;
    private javax.swing.JRadioButtonMenuItem jrbItemAmarillo;
    private javax.swing.JRadioButtonMenuItem jrbItemAzul;
    private javax.swing.JRadioButtonMenuItem jrbItemDetallada;
    private javax.swing.JRadioButtonMenuItem jrbItemEspanol;
    private javax.swing.JRadioButtonMenuItem jrbItemIngles;
    private javax.swing.JRadioButtonMenuItem jrbItemMorado;
    private javax.swing.JRadioButtonMenuItem jrbItemRojo;
    private javax.swing.JRadioButtonMenuItem jrbItemRosa;
    private javax.swing.JRadioButtonMenuItem jrbItemSimple;
    // End of variables declaration//GEN-END:variables

    /**
     * Cambia el tipo de fuente recursivamente a todos los elementos que se
     * encuentran dentro de un contenedor, que puede ser un JPanel, un JMenuBar
     * o un JMenu.
     *
     * @param contenedor Es el contenedor de donde se extraeran los elementos
     * para cambiar la fuente.
     */
    private void cambiarLetraHijos(JComponent contenedor) {
        Component[] componentes;

        if (contenedor instanceof JMenu) {
            componentes = ((JMenu) contenedor).getMenuComponents();
        } else {
            componentes = contenedor.getComponents();
        }

        if (componentes.length > 0) {
            for (Component c : componentes) {
                if (c instanceof JMenuBar || c instanceof JMenu
                        || c instanceof JPanel) {
                    cambiarLetraHijos((JComponent) c);
                } else if (c instanceof JScrollPane) {
                    Component comp
                            = ((JScrollPane) c).getViewport().getComponent(0);
                    cambiarLetraHijos((JComponent) comp);
                }

                if (c instanceof JPanel) {
                    Border b = ((JPanel) c).getBorder();

                    if (b instanceof TitledBorder) {
                        ((TitledBorder) b).setTitleFont(generarFont((JComponent) c, 20));
                    }

                }

                c.setFont(generarFont((JComponent) c, 20));
            }
        } else {
            System.err.println("NO COMPONENTES DENTRO DE: " + contenedor.getClass());
        }
    }

    /**
     * Genera una fuente a partir de un JComponent, con el tamano de letra
     * indicado.
     *
     * @param componente Es el componente del cual se obtendra su fuente por
     * default.
     * @param size Es el tamano deseado para la fuente.
     * @return La fuente con las caracteristicas deseadas.
     */
    private Font generarFont(JComponent componente, int size) {
        String name = componente.getFont().getFontName();
        int style = componente.getFont().getStyle();
        return new Font(name, style, size);
    }

    /**
     * Inicializa aspectos de la gui, que no se pueden colocar en el metodo
     * initComponents.
     */
    private void iniciarGUI() {
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        cambiarLetraHijos(jMenuBar);
        cambiarLetraHijos(jPanelFondoClaro);
        
        jScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        jScrollPane.setBorder(BorderFactory.createEmptyBorder());
        jScrollPane.getViewport().setOpaque(false);
        jScrollPane.setViewportBorder(BorderFactory.createEmptyBorder());
    }
}
