package com.porfirio.fraccionando.test;

import com.porfirio.fraccionando.dominio.logica.fracciones.FraccionSimple;
import com.porfirio.fraccionando.dominio.logica.operaciones.Operacion;
import com.porfirio.fraccionando.gui.listeners.CreacionFraccionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * Esta clase prueba al panel generador de fracciones.
 *
 * @author Porfirio Angel Diaz Sanchez [porfirioads@gmail.com]
 */
public class TestFraccionPanel extends javax.swing.JFrame {

    private Operacion operacion;

    /**
     * Creates new form TestFraccionPanel
     */
    public TestFraccionPanel() {
        initComponents();
        iniciarOperacion();
        setLocationRelativeTo(null);

        fraccionPanel1.setFracciones(operacion.getFracciones());

        fraccionPanel1.setCreacionFraccionListener(
                new CreacionFraccionListener() {

                    @Override
                    public void onFraccionUpdated() {
                        updateGUI();
                    }

                    @Override
                    public void onFraccionRemoved() {
                        updateGUI();
                    }

                    @Override
                    public void onFraccionReseted() {
                        updateGUI();
                    }
                });

        updateGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldFraccionString = new javax.swing.JTextField();
        jTextFieldFraccionLatex = new javax.swing.JTextField();
        jTextFieldFraccionLatexFormulacion = new javax.swing.JTextField();
        jButtonAgregarFraccion = new javax.swing.JButton();
        jButtonReiniciarOperacion = new javax.swing.JButton();
        jButtonResolverOperacion = new javax.swing.JButton();
        fraccionPanel1 = new com.porfirio.fraccionando.gui.componentes.FraccionPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(6, 0));
        jPanel1.add(jTextFieldFraccionString);
        jPanel1.add(jTextFieldFraccionLatex);
        jPanel1.add(jTextFieldFraccionLatexFormulacion);

        jButtonAgregarFraccion.setText("Agregar fraccion");
        jButtonAgregarFraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarFraccionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAgregarFraccion);

        jButtonReiniciarOperacion.setBackground(new java.awt.Color(0, 153, 153));
        jButtonReiniciarOperacion.setText("Reiniciar operacion");
        jButtonReiniciarOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReiniciarOperacionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReiniciarOperacion);

        jButtonResolverOperacion.setText("Resolver operacion");
        jButtonResolverOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResolverOperacionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonResolverOperacion);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(fraccionPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarFraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarFraccionActionPerformed
        operacion.getOperadores().add('+');
        operacion.getFracciones().add(new FraccionSimple());
        fraccionPanel1.updateGUI();
        updateGUI();
    }//GEN-LAST:event_jButtonAgregarFraccionActionPerformed

    private void jButtonReiniciarOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReiniciarOperacionActionPerformed
        iniciarOperacion();
        updateGUI();
    }//GEN-LAST:event_jButtonReiniciarOperacionActionPerformed

    private void jButtonResolverOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResolverOperacionActionPerformed
        JOptionPane.showMessageDialog(TestFraccionPanel.this, "Yo resuelvo.");
    }//GEN-LAST:event_jButtonResolverOperacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestFraccionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestFraccionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestFraccionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestFraccionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFraccionPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.porfirio.fraccionando.gui.componentes.FraccionPanel fraccionPanel1;
    private javax.swing.JButton jButtonAgregarFraccion;
    private javax.swing.JButton jButtonReiniciarOperacion;
    private javax.swing.JButton jButtonResolverOperacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldFraccionLatex;
    private javax.swing.JTextField jTextFieldFraccionLatexFormulacion;
    private javax.swing.JTextField jTextFieldFraccionString;
    // End of variables declaration//GEN-END:variables

    private void updateGUI() {
        if (fraccionPanel1.isCompleta()) {
            jButtonAgregarFraccion.setEnabled(true);
        } else {
            jButtonAgregarFraccion.setEnabled(false);
        }

        if (operacion.getFracciones().size() > 1) {
            jButtonReiniciarOperacion.setEnabled(true);
        } else if (operacion.getFracciones().size() == 1) {
            if (fraccionPanel1.getFraccion().equals(new FraccionSimple())) {
                jButtonReiniciarOperacion.setEnabled(false);
            } else {
                jButtonReiniciarOperacion.setEnabled(true);
            }
        }

        if (operacion.getFracciones().size() > 1) {
            if (fraccionPanel1.isCompleta()) {
                jButtonResolverOperacion.setEnabled(true);
            } else {
                jButtonResolverOperacion.setEnabled(false);
            }
        } else {
            jButtonResolverOperacion.setEnabled(false);
        }

        jTextFieldFraccionString.setText(operacion.toString());
        jTextFieldFraccionLatex.setText(operacion.toLatex(false));
        jTextFieldFraccionLatexFormulacion.setText(operacion.toLatex(true));
    }

    private void iniciarOperacion() {
        operacion = new Operacion(new ArrayList<>(), new ArrayList<>());
        fraccionPanel1.setFracciones(operacion.getFracciones());
        fraccionPanel1.setOperadores(operacion.getOperadores());
    }
}
